### PR TITLE
Velocity 3.0.0 compatibility

### PR DESCRIPTION
**Pull request by AlbeMiglio**
+ Added Velocity 3.0.x compatibility
- Removed TextFormat usage

### CODE REVIEW

**Comment by benwoo1110** [comment]
#336 already did it?

**Comment by AlbeMiglio** [comment]
I've just imported the latest 0.5.0-SNAPSHOT released version on Maven and it didn't work, so I forked a fix. Have a look, otherwise I may close the PR.

**Comment by benwoo1110** [comment]
Well yea... the PR is not merged yet, so it's not in maven. But it's already up for review.

**Comment by AlbeMiglio** [comment]
If someone needs an urgent maven import, my fork (
https://github.com/AlbeMiglio/ACF) is available on jitpack.io - then feel
free to review the PR whenever you want.

Il lun 13 set 2021, 17:59 Ben Woo ***@***.***> ha scritto:

**Pull request merged**
