### PR TITLE
[acf-jda] Update to JDA version 4

### PR DESCRIPTION
**Pull request by NickAcPT**
Updated the JDA version to the latest beta version.
Most changes were package changes.

I haven't changed the version number or any documentation since I don't know what to do.

### CODE REVIEW

**Comment by MiniDigger** [comment]
I know @MrDienns gave this ago early this month and faced some issues, maybe he can take a look at this?

**Comment by NickAcPT** [comment]
All I did was to change the packages and I didn't notice any issue as of now.

**Comment by NickAcPT** [comment]
Will this ever get merged?

**Comment by MrIvanPlays** [comment]
> Will this ever get merged?

Same. Also you could update version again, we're at 4.1.0_105

**Comment by aikar** [comment]
Please reopen this once JDA4 is not in beta.

ACF has a single version release. This would be rather inconvenient to anyone who is still needing to be on JDA3.

**Comment by MrIvanPlays** [comment]
> Please reopen this once JDA4 is not in beta.
> 
> ACF has a single version release. This would be rather inconvenient to anyone who is still needing to be on JDA3.

JDA4 is already out of beta. The PR was out of date.

**Pull request closed without merging**
