### PR TITLE
Updated JDA support 4.2

### PR DESCRIPTION
**Pull request by darbyjack**
This needs to be tested.

### CODE REVIEW

**Comment by Chasewhip8** [comment]
Doesnt seem to be funtioning at all. 
Test code:
```java
    public RaidControl(String token){
        try {
            jda = JDABuilder.createDefault(token).build();
        } catch (LoginException e){
            e.printStackTrace();
            return;
        }

        JDACommandManager commandManager = new JDACommandManager(jda);

        commandManager.registerCommand(new TestCommand());
    }
```
```java
@CommandAlias("test")
public class TestCommand extends BaseCommand {
    @Default
    public void on1(){
        System.out.println("test");
    }
}
```

**Comment by aggellos2001** [comment]
We need that!

**Comment by MrDienns** [comment]
Any update on this?

**Comment by aikar** [comment]
I'll see if i can do whats needed here soon. I want to release a final build of jda3 under a diff artifact name but need to see how i want to do that.

**Comment by JarFiles** [comment]
Is there an eta when the jda module of your acf will be finished? If not, is there a list of things that need to be done so I can implement then by myself?

**Review by aikar — APPROVED** [review]

**Comment by aikar** [comment]
Anyone previously using jda3 and needs to stay on it until transition is complete to jda4
switch the following artifacts in your build to the final jda3 builds

acf-core -> acf-corejda3final  0.5.0-SNAPSHOT
acf-jda -> acf-da3final  0.5.0-SNAPSHOT

**Pull request merged**
