### PR TITLE
Add support for Folia. Closes #386

### LINKED ISSUE #386: Add support to Folia if it possible
Folia url: https://github.com/PaperMC/Folia

Thanks 😄

### PR DESCRIPTION
**Pull request by creatorfromhell**
- Added a new Scheduler class to managing all scheduling.

### CODE REVIEW

**Comment by creatorfromhell** [comment]
@chickeneer This PR is ready for review. I marked it as a draft the last time because I forgot to test the last push on both regular paper and Folia, but I have since tested both. You may test again if you would like.

**Comment by chickeneer** [comment]
I will try and get it reviewed/merged tonight. 👍

**Comment by creatorfromhell** [comment]
> I will try and get it reviewed/merged tonight. 👍

👍 If you have any questions feel free to let me know here, or also on discord.

**Comment by chickeneer** [comment]
I have merged this and deployed

**Pull request merged**
