### PR TITLE
[Draft] Help improvements: detailed param help, headers...

### PR DESCRIPTION
**Pull request by MiniDigger**
Example:
code: https://github.com/VoxelGamesLib/VoxelGamesLibv2/blob/b02becffc6ee6c9e7685d88d2f264fee14cd37aa/VoxelGamesLib/src/main/java/com/voxelgameslib/voxelgameslib/command/commands/StatsCommands.java
normal help:

detailed param help:

search:

ToDo/Open questions:
- [ ] add proper formatters so that platforms can customize help formatting (think hover messages for minecraft platforms)
- [ ] what about params with no description? https://github.com/aikar/commands/commit/a26eb31a041c9657ab3c0a80e6ab91a3a3817fd5#diff-b3fa5ad87f01cbeccbb1ccaf1b05338cR51
- [ ] display detailed help in search?
- [ ] add message to help discover detailed help (as footer for normal help?)
- [x] remove sender field from param syntax (`/stats increment [sender] [user] <type> [amount]` needs to be `/stats increment <user> <type> [amount]`)
- [ ] nicer header for search
- [ ] makes this nicer https://github.com/aikar/commands/pull/106/commits/a4c67f66a2bbdb413a87d380d678183a46883073

### CODE REVIEW

**Comment by MrDienns** [comment]
@MiniDigger for president

**Comment by Proximyst** [comment]
@MrDienns thats gay

**Comment by Chazmondo** [comment]
This looks awesome, makes it easier to provide help for our users. I take it this would use the Bukkit Message system that is used for the command syntax colors?

**Comment by MiniDigger** [comment]
Yes, it currently uses the color system all other language files use. Later today I want to abstract out the formatting, allowing platforms to further customize help pages, for adding stuff like hover texts for example.

**Comment by Chazmondo** [comment]
I can't wait to use it, looks awesome. Would be nice if we could fully change the text or use a "builder" to create header / footer and the command format.

**Comment by aikar** [comment]
So far looks good with no real concerns.

Don't forget to add verifyUnstableAPI("help"); to the new manager methods

**Comment by aikar** [comment]
@MiniDigger I'm going to manually merge and get this to a deployable state for current progress. So you can resume off top of that.

**Comment by MiniDigger** [comment]
Sorry that I didn't get back to this last week, was kinda busy for me, what is still open now? I guess the chat component trickery?

**Pull request merged**
